### PR TITLE
only consider iface with mode=ap

### PR DESCRIPTION
**Pull request by petzah**

### CODE REVIEW

**Comment by petzah** [comment]
hmm, maybe it should be rewritten to mode!=sta

**Comment by barbieri** [comment]
i think there is only sta and ap, do you know of others?

otherwise looks good to me

**Comment by petzah** [comment]
There are ap, sta, adhoc, wds, monitor and mesh modes: https://openwrt.org/docs/guide-user/network/wifi/basic#common_options1

I was thinking that maybe mesh(802.11s) is kind of ap but don't have any experience with it. 99% of the time users are configuring either "ap" or "sta" mode so it should be fine.

**Comment by barbieri** [comment]
ah, I always forget about those. I'll merge as is, if something else is needed, it's easy to change and we come back to it later.

Thanks

**Pull request merged**
